create table if not exists public.bot_state (
  id bigint primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_events (
  id bigint generated by default as identity primary key,
  event jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.bot_state enable row level security;
alter table public.trade_events enable row level security;
